### ISSUE TITLE
The api_id/api_hash combination is invalid

### ISSUE THREAD

**Issue by maikelrichard** [GentlemanHu/TelegramForwarder#1]
The api_id/api_hash combination is invalid

my api not working even if the credentials are correct

**Comment by GentlemanHu** [comment]
https://github.com/GentlemanHu/TelegramForwarder/blob/f2ca9d7b832a8d197413a306648d9239aa68876a/config.py#L10

you can manually configure it in `config.py`. 
I will fix the env loading bug soon.

**Comment by GentlemanHu** [comment]
fixed
